apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-prod
spec:
  podSelector:
    matchLabels:
      environment: prod
  policyTypes:
    - Ingress
    - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-pacman
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: pacman
      app.kubernetes.io/component: frontend
      environment: prod
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pacman-to-mongodb
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: pacman
      app.kubernetes.io/component: frontend
      environment: prod
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: pacman
              app.kubernetes.io/component: database
              environment: prod
      ports:
        - protocol: TCP
          port: 27017

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mongodb-from-pacman
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: pacman
      app.kubernetes.io/component: database
      environment: prod
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: pacman
              app.kubernetes.io/component: frontend
              environment: prod
      ports:
        - protocol: TCP
          port: 27017

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-prod
spec:
  podSelector:
    matchLabels:
      environment: prod
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53