apiVersion: v1
kind: ResourceQuota
metadata:
  name: pacman-namespace-quota
spec:
  hard:
    requests.cpu: 750m
    requests.memory: 768Mi
    limits.cpu: "2"
    limits.memory: 1536Mi
    pods: "6"
    persistentvolumeclaims: "2"
