apiVersion: v1
kind: ServiceAccount

metadata:
  name: pacman
  labels:
    app.kubernetes.io/name: pacman
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: pacman-platform
    app.kubernetes.io/managed-by: argocd
    responsibility: devops

# Die Anwendung benötigt keinen Zugriff auf die Kubernetes-API.
# Deshalb wird kein ServiceAccount-Token in den Pod eingebunden.
automountServiceAccountToken: false