apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pacman-prod

resources:
  - namespace.yaml
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/instance: pacman-prod  # Eindeutige Instanz-ID dieser Bereitstellung (grenzt prod von dev ab)
      environment: prod                         # Kennzeichnet die Umgebung als Produktion
    includeTemplates: true                      # Labels auch ins Pod-Template übernehmen, damit NetworkPolicy-podSelectoren auf "environment: prod" greifen

replicas:
  - name: pacman
    count: 3

images:
  - name: ghcr.io/isangare-ux/pacman-app
    newTag: dfe16c3c188e5011a8fa91324524fb63aaf91a91
    