apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pacman
  labels:
    app.kubernetes.io/name: pacman
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: pacman
